### ISSUE TITLE
Fix: Extra line added when saving without markup and loading back in

### ISSUE THREAD

**Issue by lspector** [benfb/gorilla-repl#1]
Saving without markup and then loading back in adds an extra newline at the end. These accumulate over time, and even the first one generates unhelpful git diffs.

Previously added as [https://github.com/JonyEpsilon/gorilla-repl/issues/286](https://github.com/JonyEpsilon/gorilla-repl/issues/286)

**Comment by benfb** [comment]
Hmm the template should be pulling in the latest. Can you confirm that the `lein-gorilla` version is at least `0.5.2`?

**Comment by lspector** [comment]
Alas, it isn't:

```
MacBook-Pro-8:temp leespector$ date
Fri Nov 23 23:48:32 EST 2018
MacBook-Pro-8:temp leespector$ lein new gorilla-app foo
Generating fresh 'lein new' gorilla-app project.
MacBook-Pro-8:temp leespector$ cd foo
MacBook-Pro-8:foo leespector$ grep gorilla project.clj
  :plugins [[org.clojars.benfb/lein-gorilla "0.5.1"]]
```

**Comment by benfb** [comment]
Interesting:

```
$ lein new gorilla-app test-me
Retrieving gorilla-app/lein-template/0.6.3/lein-template-0.6.3.pom from clojars
Retrieving gorilla-app/lein-template/0.6.3/lein-template-0.6.3.jar from clojars
Generating fresh 'lein new' gorilla-app project.
```
I wonder if there's a way to force the template download? Maybe `rm -r ~/.m2/repository/gorilla-app`?

**Comment by lspector** [comment]
That worked!

```
MacBook-Pro-8:temp leespector$ lein new gorilla-app foo
Retrieving gorilla-app/lein-template/0.6.3/lein-template-0.6.3.pom from clojars
Retrieving gorilla-app/lein-template/0.6.3/lein-template-0.6.3.jar from clojars
Generating fresh 'lein new' gorilla-app project.
MacBook-Pro-8:temp leespector$ cd foo
MacBook-Pro-8:foo leespector$ grep gorilla project.clj
  :plugins [[org.clojars.benfb/lein-gorilla "0.5.3"]]
```

So I'm personally now in good shape for the moment... but it sure would be nice if everyone else who ever previously used the template wouldn't have to learn this trick in order to get the latest (and if I wouldn't have to remember it in order to get your future updates).

**Comment by benfb** [comment]
Great! If you haven't had to do that in the past to pick up updates, I'm going to assume that it automatically pings the clojars repo to get the latest updates for a template after a while and we just weren't giving it enough time. Otherwise, I can't find a way to force leiningen to get the latest.
